const characters = [
    {
        id: 1,
        charName: "Mithandir",
        race: "Elfo",
        charClass: "Mago",
        level: 5,
        gold: 2500,
        playerName: "Eugenio",
        isActive: true,
    },
    {
        id: 2,
        charName: "Heos",
        race: "Humano",
        charClass: "Paladín",
        level: 6,
        gold: 450,
        playerName: "Carlos",
        isActive: true,
    },
    {
        id: 3,
        charName: "Melkor",
        race: "Orco",
        charClass: "Mercenario",
        level: 8,
        gold: 1480,
        playerName: "Pablo",
        isActive: false,
    },
    {
        id: 4,
        charName: "Yorim",
        race: "Enano",
        charClass: "Guerrero",
        level: 4,
        gold: 300,
        playerName: "Javier",
        isActive: true,
    },
];